controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
vinyl_browse:
    path: /browse/{slug}
    controller: App\Controller\VinylController::browse
homepage:
    path: /homepage
    controller: App\Controller\VinylController::homepage
